'use strict';

// Artist tracks for the "artists" music mode. Every entry is shown on the
// in-game now-playing card with the artist credited and linked — that card
// is the attribution the licenses ask for. `worlds` ties a track to specific
// worlds; tracks without it form the anywhere pool, blended into every world.
//
// `spotify`/`apple` power the platform buttons on the card (generated by
// tools/resolve_links.py + apply_links.py — plain links only, no SDKs:
// Spotify's developer terms prohibit API use in games). Tracks missing a
// link simply don't show that button.
//
// Curation bar: nothing faster or busier than Heart Of The Ocean.
const TRACKS = [
  // meadow
  {
    src: 'music/Wildflowers.mp3',
    title: 'Wildflowers', artist: 'Purrple Cat',
    link: 'https://soundcloud.com/purrplecat', license: 'CC BY-SA 3.0',
    spotify: 'https://open.spotify.com/search/Purrple%20Cat%20Wildflowers',
    apple: 'https://music.apple.com/us/album/wildflowers/1757304523?i=1757304743',
    worlds: ['meadow'],
  },
  {
    src: 'music/Bloom.mp3',
    title: 'Bloom', artist: 'Purrple Cat',
    link: 'https://soundcloud.com/purrplecat', license: 'CC BY-SA 3.0',
    spotify: 'https://open.spotify.com/search/Purrple%20Cat%20Bloom',
    apple: 'https://music.apple.com/us/album/bloom/1501106939?i=1501106941',
    worlds: ['meadow'],
  },
  {
    src: 'music/Butterfly.mp3',
    title: 'Butterfly', artist: 'Purrple Cat',
    link: 'https://soundcloud.com/purrplecat', license: 'CC BY-SA 3.0',
    spotify: 'https://open.spotify.com/search/Purrple%20Cat%20Butterfly',
    apple: 'https://music.apple.com/us/album/butterfly/1757304523?i=1757304744',
    worlds: ['meadow'],
  },
  // midnight
  {
    src: 'music/Crescent Moon.mp3',
    title: 'Crescent Moon', artist: 'Purrple Cat',
    link: 'https://soundcloud.com/purrplecat', license: 'CC BY-SA 3.0',
    spotify: 'https://open.spotify.com/search/Purrple%20Cat%20Crescent%20Moon',
    apple: 'https://music.apple.com/us/album/crescent-moon/1560910162?i=1560910163',
    worlds: ['midnight'],
  },
  {
    src: 'music/Sonder.mp3',
    title: 'Sonder', artist: 'Purrple Cat',
    link: 'https://soundcloud.com/purrplecat', license: 'CC BY-SA 3.0',
    spotify: 'https://open.spotify.com/search/Purrple%20Cat%20Sonder',
    apple: 'https://music.apple.com/us/album/sonder/1716265693?i=1716265854',
    worlds: ['midnight'],
  },
  {
    src: 'music/Field Of Fireflies.mp3',
    title: 'Field Of Fireflies', artist: 'Purrple Cat',
    link: 'https://soundcloud.com/purrplecat', license: 'CC BY-SA 3.0',
    spotify: 'https://open.spotify.com/search/Purrple%20Cat%20Field%20Of%20Fireflies',
    apple: 'https://music.apple.com/us/album/field-of-fireflies/1520764945?i=1520764956',
    worlds: ['midnight'],
  },
  // classic — deliberately retro, the one upbeat exception
  {
    src: 'music/Pixelland.mp3',
    title: 'Pixelland', artist: 'Kevin MacLeod',
    link: 'https://incompetech.com', license: 'CC BY 4.0',
    spotify: 'https://open.spotify.com/search/Kevin%20MacLeod%20Pixelland',
    apple: 'https://music.apple.com/us/album/pixelland/1887666187?i=1887666578',
    worlds: ['classic'],
  },
  {
    src: 'music/Bit Quest.mp3',
    title: 'Bit Quest', artist: 'Kevin MacLeod',
    link: 'https://incompetech.com', license: 'CC BY 4.0',
    spotify: 'https://open.spotify.com/search/Kevin%20MacLeod%20Bit%20Quest',
    apple: 'https://music.apple.com/us/album/bit-quest/1887666187?i=1887666190',
    worlds: ['classic'],
  },
  // sakura
  {
    src: 'music/Green Tea.mp3',
    title: 'Green Tea', artist: 'Purrple Cat',
    link: 'https://soundcloud.com/purrplecat', license: 'CC BY-SA 3.0',
    spotify: 'https://open.spotify.com/search/Purrple%20Cat%20Green%20Tea',
    apple: 'https://music.apple.com/us/album/green-tea/1501106939?i=1501106944',
    worlds: ['sakura'],
  },
  {
    src: 'music/Ishikari Lore.mp3',
    title: 'Ishikari Lore', artist: 'Kevin MacLeod',
    link: 'https://incompetech.com', license: 'CC BY 4.0',
    spotify: 'https://open.spotify.com/search/Kevin%20MacLeod%20Ishikari%20Lore',
    apple: 'https://music.apple.com/us/album/ishikari-lore/1887660728?i=1887662063',
    worlds: ['sakura'],
  },
  {
    src: 'music/Spring Showers.mp3',
    title: 'Spring Showers', artist: 'Purrple Cat',
    link: 'https://soundcloud.com/purrplecat', license: 'CC BY-SA 3.0',
    spotify: 'https://open.spotify.com/search/Purrple%20Cat%20Spring%20Showers',
    apple: 'https://music.apple.com/us/album/spring-showers/1501106939?i=1501106943',
    worlds: ['sakura'],
  },
  // tide — the benchmark
  {
    src: 'music/Heart Of The Ocean.mp3',
    title: 'Heart Of The Ocean', artist: 'Purrple Cat',
    link: 'https://soundcloud.com/purrplecat', license: 'CC BY-SA 3.0',
    spotify: 'https://open.spotify.com/search/Purrple%20Cat%20Heart%20Of%20The%20Ocean',
    apple: 'https://music.apple.com/us/album/heart-of-the-ocean/1575832220?i=1575832221',
    worlds: ['tide'],
  },
  {
    src: 'music/Calm Waters.mp3',
    title: 'Calm Waters', artist: 'Purrple Cat',
    link: 'https://soundcloud.com/purrplecat', license: 'CC BY-SA 3.0',
    spotify: 'https://open.spotify.com/search/Purrple%20Cat%20Calm%20Waters',
    apple: 'https://music.apple.com/us/album/calm-waters/1520764945?i=1520764957',
    worlds: ['tide'],
  },
  {
    src: 'music/Where The Waves Take Us.mp3',
    title: 'Where The Waves Take Us', artist: 'Purrple Cat',
    link: 'https://soundcloud.com/purrplecat', license: 'CC BY-SA 3.0',
    spotify: 'https://open.spotify.com/search/Purrple%20Cat%20Where%20The%20Waves%20Take%20Us',
    apple: 'https://music.apple.com/us/album/where-the-waves-take-us/6770656368?i=6770656371',
    worlds: ['tide'],
  },
  // autumn
  {
    src: 'music/Golden Hour.mp3',
    title: 'Golden Hour', artist: 'Purrple Cat',
    link: 'https://soundcloud.com/purrplecat', license: 'CC BY-SA 3.0',
    spotify: 'https://open.spotify.com/search/Purrple%20Cat%20Golden%20Hour',
    apple: 'https://music.apple.com/us/album/golden-hour/1757304523?i=1757304528',
    worlds: ['autumn'],
  },
  {
    src: 'music/Cozy Fireplace.mp3',
    title: 'Cozy Fireplace', artist: 'Purrple Cat',
    link: 'https://soundcloud.com/purrplecat', license: 'CC BY-SA 3.0',
    spotify: 'https://open.spotify.com/search/Purrple%20Cat%20Cozy%20Fireplace',
    apple: 'https://music.apple.com/us/album/cozy-fireplace/1486975182?i=1486975192',
    worlds: ['autumn'],
  },
  {
    src: 'music/Equinox.mp3',
    title: 'Equinox', artist: 'Purrple Cat',
    link: 'https://soundcloud.com/purrplecat', license: 'CC BY-SA 3.0',
    spotify: 'https://open.spotify.com/search/Purrple%20Cat%20Equinox',
    apple: 'https://music.apple.com/us/album/equinox/1501106939?i=1501106945',
    worlds: ['autumn'],
  },
  // mono
  {
    src: 'music/Gymnopedie No 1.mp3',
    title: 'Gymnopédie No. 1', artist: 'Erik Satie, perf. Kevin MacLeod',
    link: 'https://incompetech.com', license: 'CC BY 4.0',
    spotify: 'https://open.spotify.com/search/Kevin%20MacLeod%20Gymnop%C3%A9die%20No.%201',
    worlds: ['mono'],
  },
  {
    src: 'music/Gymnopedie No 2.mp3',
    title: 'Gymnopédie No. 2', artist: 'Erik Satie, perf. Kevin MacLeod',
    link: 'https://incompetech.com', license: 'CC BY 4.0',
    spotify: 'https://open.spotify.com/search/Kevin%20MacLeod%20Gymnop%C3%A9die%20No.%202',
    worlds: ['mono'],
  },
  {
    src: 'music/Gymnopedie No 3.mp3',
    title: 'Gymnopédie No. 3', artist: 'Erik Satie, perf. Kevin MacLeod',
    link: 'https://incompetech.com', license: 'CC BY 4.0',
    spotify: 'https://open.spotify.com/search/Kevin%20MacLeod%20Gymnop%C3%A9die%20No.%203',
    worlds: ['mono'],
  },
  // storm
  {
    src: 'music/Storm Clouds.mp3',
    title: 'Storm Clouds', artist: 'Purrple Cat',
    link: 'https://soundcloud.com/purrplecat', license: 'CC BY-SA 3.0',
    spotify: 'https://open.spotify.com/search/Purrple%20Cat%20Storm%20Clouds',
    apple: 'https://music.apple.com/us/album/storm-clouds/6770656368?i=6770656595',
    worlds: ['storm'],
  },
  {
    src: 'music/Thunder Nap.mp3',
    title: 'Thunder Nap', artist: 'Purrple Cat',
    link: 'https://soundcloud.com/purrplecat', license: 'CC BY-SA 3.0',
    spotify: 'https://open.spotify.com/search/Purrple%20Cat%20Thunder%20Nap',
    apple: 'https://music.apple.com/us/album/thunder-nap/6770631007?i=6770631382',
    worlds: ['storm'],
  },
  {
    src: 'music/Rainy Streets.mp3',
    title: 'Rainy Streets', artist: 'Purrple Cat',
    link: 'https://soundcloud.com/purrplecat', license: 'CC BY-SA 3.0',
    spotify: 'https://open.spotify.com/search/Purrple%20Cat%20Rainy%20Streets',
    apple: 'https://music.apple.com/us/album/rainy-streets/1716265693?i=1716265696',
    worlds: ['storm'],
  },
  // anywhere
  {
    src: 'music/Daydreams.mp3',
    title: 'Daydreams', artist: 'Purrple Cat',
    link: 'https://soundcloud.com/purrplecat', license: 'CC BY-SA 3.0',
    spotify: 'https://open.spotify.com/search/Purrple%20Cat%20Daydreams',
    apple: 'https://music.apple.com/us/album/daydreams/1757304523?i=1757304524',
  },
];
